### ISSUE TITLE
Unmatch gender from database and bar chart

### ISSUE THREAD

**Issue by Supakrit65** [SPaM-Skill-Issue/sota-frontend#11]
<img width="505" alt="image" src="https://github.com/SPaM-Skill-Issue/sota-frontend/assets/92836314/6cf979eb-60a2-44f5-b69a-4932b63b7f2f">

There should be two felmale and 1 male for sport 1.

<img width="1470" alt="image" src="https://github.com/SPaM-Skill-Issue/sota-frontend/assets/92836314/6a75d724-8a68-4230-9bed-70bb154070c0">

_Originally posted by @Supakrit65 in https://github.com/SPaM-Skill-Issue/sota-frontend/issues/10#issuecomment-1807521404_

**Comment by RyukungG** [comment]
Close in commit #[396cdf7](https://github.com/SPaM-Skill-Issue/sota-frontend/pull/10/commits/396cdf77b4241a1d3d1a8ec4692e0e9afbba2f6c)
